name: Deploy Infrastructure

on:
  push:
    branches:
      - main  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Get EC2 Public IP
        id: get_ec2_ip
        run: |
          EC2_IP=$(terraform output instance_id | tr -d '\n')
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV
      
      - name: Install Python and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
  
      - name: Install AWS CLI using pip
        run: |
          sudo pip3 install awscli

      - name: Retrieve SSH Key from AWS SSM
        run: |
          aws ssm get-parameter --name "deployer-key" --with-decryption --region us-east-1 --query "Parameter.Value" --output text > deployer-key.pem
          chmod 600 deployer-key.pem

      - name: Deploy Docker container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i deployer-key.pem ubuntu@$EC2_IP << 'EOF'
          # Descargar e iniciar el contenedor desde Docker Hub
          sudo docker pull danieljimenez357/web
          
          # Ejecutar el nuevo contenedor
          sudo docker run -d \
            --name my-apache-ssl \
            --restart=always \
            -p 80:80 \
            -p 443:443 \
            -v /home/ubuntu/apache-certificate.crt:/etc/apache2/crt/apache-certificate.crt \
            -v /home/ubuntu/apache.key:/etc/apache2/crt/apache.key \
            danieljimenez357/web
          EOF
  
      - name: Clean up SSH Key
        run: rm -f deployer-key.pem
